name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install standard-version
        run: npm install --save-dev standard-version

      - name: Check if new version exists
        id: version-check
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if git rev-parse "v$CURRENT_VERSION" >/dev/null 2>&1; then
            echo "Version v$CURRENT_VERSION already exists. Skipping publish."
            echo "publish=false" >> $GITHUB_OUTPUT
          else
            echo "New version detected: v$CURRENT_VERSION"
            echo "publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        if: steps.version-check.outputs.publish == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTOMATIONTOKEN }}

      - name: Push Git tag
        if: steps.version-check.outputs.publish == 'true'
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v$VERSION"
          git push origin "v$VERSION"
